### ISSUE TITLE
Setting "cmd" as windowsShell breaks

### ISSUE THREAD

**Issue by davidebeatrici** [KnicKnic/os-specific-run#9]
> Error: Unable to locate executable file: %ComSpec%. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

**Comment by davidebeatrici** [comment]
Thank you very much for the fast fix!

**Comment by KnicKnic** [comment]
@davidebeatrici I pushed release v1.0.4 It contains the necessary fix.

**Comment by davidebeatrici** [comment]
I confirm it works, thank you again!

SoftEtherVPN/libhamcore@ba137e665664221562427c4381d88ba6ad6e1e9a
